const state = {
  graphData: null,
  complexityLevel: 0.99,
  importanceScores: null,
  clusterTimer: null,
  expandedClusters: new Set(),
  expandedLibClusters: new Set(),
  connectedNodeIds: new Set(),
  simulation: null,
  svgNodes: null,
  svgLinks: null,
  svgLabels: null,
  svgLibNodes: null,
  svgLibLabels: null,
  currentNodes: [],
  currentZoom: 1,
  hasFitted: false,
  pendingReheat: false,
  layoutMode: 'dynamic',
  gitMode: true,
  languageMode: true,
  folderMode: true,
  classMode: true,
  svgFileCircles: null,
  svgFolderBubbles: null,
  svgClassBubbles: null,
  gitAvailable: false,
  activeLibNode: null,
  libDescRequestId: 0,
  activeFuncNode: null,
  funcSourceRequestId: 0,
  originalFuncSource: null,
  funcCardDragged: false,
  funcCardX: 0,
  funcCardY: 0,
  funcCardW: 0,
  funcCardH: 0,
};
