const state = {
  graphData: null,
  complexityLevel: 1,
  clusterGroupBy: 'connectivity',  // 'connectivity' | 'class' | 'file' | 'folder'
  importanceScores: null,
  clusterTimer: null,
  expandedClusters: new Set(),
  expandedLibClusters: new Set(),
  connectedNodeIds: new Set(),
  simulation: null,
  svgNodes: null,
  svgCloudNodes: null,
  svgLinks: null,
  svgLabels: null,
  svgLibNodes: null,
  svgLibLabels: null,
  currentNodes: [],
  currentZoom: 1,
  hasFitted: false,
  pendingReheat: false,
  layoutMode: 'dynamic',
  gitMode: true,
  languageMode: true,
  folderMode: true,
  classMode: true,
  svgFileCircles: null,
  svgFolderBubbles: null,
  svgClassBubbles: null,
  gitAvailable: false,
  activeLibNode: null,
  libDescRequestId: 0,
  funcPopups: new Map(),
  funcPopupZCounter: 200,
  allScannedFiles: [],
  hiddenFolders: new Set(),
  onlyShowFolder: null,
};
